/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2010-2011 OpenCFD Ltd.
     \\/     M anipulation  |
-------------------------------------------------------------------------------
                            | Copyright (C) 2011-2015 OpenFOAM Foundation
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

Application
    ERFFoam

Group
    grpElectroMagneticsSolvers

Description
Solver for the electromagnetic field generated by RF current field.

    A Poisson's equation for the magnetic scalar potential psi is solved
    from which the magnetic field intensity H and magnetic flux density B
    are obtained.  The paramagnetic particle force field (H dot grad(H))
    is optionally available.

\*---------------------------------------------------------------------------*/

#include "fvCFD.H"
#include "electromagneticConstants.H"
#include "simpleControl.H"
#include "fvOptions.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

int main(int argc, char *argv[])
{
    argList::addNote
    (
        "Solver for the electromagnetic field generated by RF current field."
    );

	#include "postProcess.H"
	#include "addCheckCaseOptions.H"
	#include "setRootCaseLists.H"
	#include "createTime.H"
	#include "createMesh.H"
	#include "createControl.H"
    #include "createFields.H"

    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

	Info  << nl << "Calculating the electromagnetic field potentials" << endl;

	while (simple.loop())
	{
		fvScalarMatrix phiEqn
		(
			fvm::laplacian(sigmam,phi)
		);
		
		phiEqn.relax();
		phiEqn.solve();
		
		Jc = -sigmam*fvc::grad(phi);
	}

	simpleControl simpleMain(mesh);

    while (simpleMain.loop())
    {
		Info  << nl << "Time = " << runTime.timeName() << nl << endl;

			fvVectorMatrix ArEqn
			(
				fvm::laplacian(Ar) + mu0_*sigmam*omegam*Ai
				==
				- mu0_*Jc
			);

			ArEqn.relax();
			ArEqn.solve();

			fvVectorMatrix AiEqn
			(
				fvm::laplacian(Ai) - mu0_*sigmam*omegam*Ar
			);

			AiEqn.relax();
			AiEqn.solve();

		Info << nl << "Calculating derived Fields" << endl;

		B = fvc::curl(Ar - Ai);
		E = omegam*(Ar + Ai);
		Jind = sigmam*E;

		Info<< nl << endl;

		runTime.write();

		runTime.printExecutionTime(Info);
    }

    Info<< "\nEnd\n" << endl;

    return 0;
}


// ************************************************************************* //
